module.exports = {
  notes: [
    {
      type: 'category',
      label: 'Linux',
      collapsed: true,
      items: [
        'linux/linux',
        'linux/suckless',
        'linux/setting-up',
        'linux/vim',
        'linux/emacs',
        'linux/tmux',
        'linux/git',
        'linux/grep',
        'linux/sed',
        'linux/awk',
        'linux/find',
        'linux/curl',
        'linux/wget',
        'linux/ssh',
        'linux/pgp',
        'linux/rsync',
        'linux/shells',
        'linux/window-managers',
        'linux/terminal-emulators',
        'linux/text-editors-and-ides',
        'linux/browsers',
      ],
    },
    {
      type: 'category',
      label: 'Programming',
      items: [
        'programming/python',
        'programming/javascript',
        'programming/typescript',
        'programming/haskell',
        'programming/rust',
        'programming/css',
        'programming/html',
      ],
    },
    {
      type: 'category',
      label: 'Recreational mathematics',
      items: [
        'mathematics/speedcubing',
        'mathematics/mathemagics',
        'mathematics/mathematics',
        'mathematics/mnemonics',
      ],
    },
    {
      type: 'category',
      label: 'Privacy',
      items: ['privacy/privacy', 'privacy/exporting-data'],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      items: [
        'miscellaneous/irc',
        'miscellaneous/websites',
        'miscellaneous/poems',
        'miscellaneous/quotes',
        'miscellaneous/misc',
      ],
    },
  ],
  books: [
    {
      type: 'category',
      label: 'Python Tricks',
      items: ['books/python-tricks/introduction', 'books/python-tricks/notes'],
    },
  ],
};
